//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXData.Chinook
{

	[Persistent(@"Artist")]
	public partial class XPOArtist : XPLiteObject
	{
		int _ArtistId;
		[Key(true)]
		public int ArtistId
		{
			get { return _ArtistId; }
			set { SetPropertyValue<int>("ArtistId", ref _ArtistId, value); }
		}
		string _Name;
		[Size(120)]
		public string Name
		{
			get { return _Name; }
			set { SetPropertyValue<string>("Name", ref _Name, value); }
		}
		[Association(@"XPOAlbumReferencesXPOArtist")]
		public XPCollection<XPOAlbum> Albums { get { return GetCollection<XPOAlbum>("Albums"); } }
	}

}
