//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXData.Chinook
{

	[Persistent(@"Employee")]
	public partial class XPOEmployee : XPLiteObject
	{
		int _EmployeeId;
		[Key(true)]
		public int EmployeeId
		{
			get { return _EmployeeId; }
			set { SetPropertyValue<int>("EmployeeId", ref _EmployeeId, value); }
		}
		string _LastName;
		[Size(20)]
		public string LastName
		{
			get { return _LastName; }
			set { SetPropertyValue<string>("LastName", ref _LastName, value); }
		}
		string _FirstName;
		[Size(20)]
		public string FirstName
		{
			get { return _FirstName; }
			set { SetPropertyValue<string>("FirstName", ref _FirstName, value); }
		}
		string _Title;
		[Size(30)]
		public string Title
		{
			get { return _Title; }
			set { SetPropertyValue<string>("Title", ref _Title, value); }
		}
		XPOEmployee _ReportsTo;
		[Association(@"XPOEmployeeReferencesXPOEmployee")]
		public XPOEmployee ReportsTo
		{
			get { return _ReportsTo; }
			set { SetPropertyValue<XPOEmployee>("ReportsTo", ref _ReportsTo, value); }
		}
		DateTime _BirthDate;
		public DateTime BirthDate
		{
			get { return _BirthDate; }
			set { SetPropertyValue<DateTime>("BirthDate", ref _BirthDate, value); }
		}
		DateTime _HireDate;
		public DateTime HireDate
		{
			get { return _HireDate; }
			set { SetPropertyValue<DateTime>("HireDate", ref _HireDate, value); }
		}
		string _Address;
		[Size(70)]
		public string Address
		{
			get { return _Address; }
			set { SetPropertyValue<string>("Address", ref _Address, value); }
		}
		string _City;
		[Size(40)]
		public string City
		{
			get { return _City; }
			set { SetPropertyValue<string>("City", ref _City, value); }
		}
		string _State;
		[Size(40)]
		public string State
		{
			get { return _State; }
			set { SetPropertyValue<string>("State", ref _State, value); }
		}
		string _Country;
		[Size(40)]
		public string Country
		{
			get { return _Country; }
			set { SetPropertyValue<string>("Country", ref _Country, value); }
		}
		string _PostalCode;
		[Size(10)]
		public string PostalCode
		{
			get { return _PostalCode; }
			set { SetPropertyValue<string>("PostalCode", ref _PostalCode, value); }
		}
		string _Phone;
		[Size(24)]
		public string Phone
		{
			get { return _Phone; }
			set { SetPropertyValue<string>("Phone", ref _Phone, value); }
		}
		string _Fax;
		[Size(24)]
		public string Fax
		{
			get { return _Fax; }
			set { SetPropertyValue<string>("Fax", ref _Fax, value); }
		}
		string _Email;
		[Size(60)]
		public string Email
		{
			get { return _Email; }
			set { SetPropertyValue<string>("Email", ref _Email, value); }
		}
		[Association(@"XPOCustomerReferencesXPOEmployee")]
		public XPCollection<XPOCustomer> Customers { get { return GetCollection<XPOCustomer>("Customers"); } }
		[Association(@"XPOEmployeeReferencesXPOEmployee")]
		public XPCollection<XPOEmployee> XPOEmployeeCollection { get { return GetCollection<XPOEmployee>("XPOEmployeeCollection"); } }
	}

}
