//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXData.Chinook
{

	[Persistent(@"Genre")]
	public partial class XPOGenre : XPLiteObject
	{
		int _GenreId;
		[Key(true)]
		public int GenreId
		{
			get { return _GenreId; }
			set { SetPropertyValue<int>("GenreId", ref _GenreId, value); }
		}
		string _Name;
		[Size(120)]
		public string Name
		{
			get { return _Name; }
			set { SetPropertyValue<string>("Name", ref _Name, value); }
		}
		[Association(@"XPOTrackReferencesXPOGenre")]
		public XPCollection<XPOTrack> Tracks { get { return GetCollection<XPOTrack>("Tracks"); } }
	}

}
