//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXData.Chinook
{

	[Persistent(@"MediaType")]
	public partial class XPOMediaType : XPLiteObject
	{
		int _MediaTypeId;
		[Key(true)]
		public int MediaTypeId
		{
			get { return _MediaTypeId; }
			set { SetPropertyValue<int>("MediaTypeId", ref _MediaTypeId, value); }
		}
		string _Name;
		[Size(120)]
		public string Name
		{
			get { return _Name; }
			set { SetPropertyValue<string>("Name", ref _Name, value); }
		}
		[Association(@"XPOTrackReferencesXPOMediaType")]
		public XPCollection<XPOTrack> Tracks { get { return GetCollection<XPOTrack>("Tracks"); } }
	}

}
