//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXData.Chinook
{

	[Persistent(@"Resources")]
	public partial class XPOResource : XPLiteObject
	{
		int _UniqueID;
		[Key(true)]
		public int UniqueID
		{
			get { return _UniqueID; }
			set { SetPropertyValue<int>("UniqueID", ref _UniqueID, value); }
		}
		int _ResourceID;
		public int ResourceID
		{
			get { return _ResourceID; }
			set { SetPropertyValue<int>("ResourceID", ref _ResourceID, value); }
		}
		string _ResourceName;
		[Size(50)]
		public string ResourceName
		{
			get { return _ResourceName; }
			set { SetPropertyValue<string>("ResourceName", ref _ResourceName, value); }
		}
		int _Color;
		public int Color
		{
			get { return _Color; }
			set { SetPropertyValue<int>("Color", ref _Color, value); }
		}
		byte[] _Image;
		[Size(SizeAttribute.Unlimited)]
		[MemberDesignTimeVisibility(true)]
		public byte[] Image
		{
			get { return _Image; }
			set { SetPropertyValue<byte[]>("Image", ref _Image, value); }
		}
		string _CustomField1;
		[Size(SizeAttribute.Unlimited)]
		public string CustomField1
		{
			get { return _CustomField1; }
			set { SetPropertyValue<string>("CustomField1", ref _CustomField1, value); }
		}
	}

}
