//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXData.Chinook
{

	[Persistent(@"Track")]
	public partial class XPOTrack : XPLiteObject
	{
		int _TrackId;
		[Key(true)]
		public int TrackId
		{
			get { return _TrackId; }
			set { SetPropertyValue<int>("TrackId", ref _TrackId, value); }
		}
		string _Name;
		[Size(200)]
		public string Name
		{
			get { return _Name; }
			set { SetPropertyValue<string>("Name", ref _Name, value); }
		}
		XPOAlbum _AlbumId;
		[Association(@"XPOTrackReferencesXPOAlbum")]
		public XPOAlbum AlbumId
		{
			get { return _AlbumId; }
			set { SetPropertyValue<XPOAlbum>("AlbumId", ref _AlbumId, value); }
		}
		XPOMediaType _MediaTypeId;
		[Association(@"XPOTrackReferencesXPOMediaType")]
		public XPOMediaType MediaTypeId
		{
			get { return _MediaTypeId; }
			set { SetPropertyValue<XPOMediaType>("MediaTypeId", ref _MediaTypeId, value); }
		}
		XPOGenre _GenreId;
		[Association(@"XPOTrackReferencesXPOGenre")]
		public XPOGenre GenreId
		{
			get { return _GenreId; }
			set { SetPropertyValue<XPOGenre>("GenreId", ref _GenreId, value); }
		}
		string _Composer;
		[Size(220)]
		public string Composer
		{
			get { return _Composer; }
			set { SetPropertyValue<string>("Composer", ref _Composer, value); }
		}
		int _Milliseconds;
		public int Milliseconds
		{
			get { return _Milliseconds; }
			set { SetPropertyValue<int>("Milliseconds", ref _Milliseconds, value); }
		}
		int _Bytes;
		public int Bytes
		{
			get { return _Bytes; }
			set { SetPropertyValue<int>("Bytes", ref _Bytes, value); }
		}
		decimal _UnitPrice;
		public decimal UnitPrice
		{
			get { return _UnitPrice; }
			set { SetPropertyValue<decimal>("UnitPrice", ref _UnitPrice, value); }
		}
		[Association(@"XPOInvoiceLineReferencesXPOTrack")]
		public XPCollection<XPOInvoiceLine> InvoiceLines { get { return GetCollection<XPOInvoiceLine>("InvoiceLines"); } }
	}

}
